### ISSUE TITLE
Turn levelOne to false

### ISSUE THREAD

**Issue by enricllagostera** [MeghanC1470/cart253#2]
https://github.com/MeghanC1470/cart253/blob/f0d19f4da06400fa399657d8424402055aee0bdd/Exercises/Project3/js/script.js#L108

I believe the issue is related to the array being re-created many times in a row. I think the solution would be to set levelOne = false right before emptying the meteor array. You'd also need to remove the "&& levelOne == true" part from line 117.  This should go into the if that repopulates the array only one, instead of every frame of levelOne.

You'd need to do that for the other levels as well.

**Comment by MeghanC1470** [comment]
Hello Enric,
I tried to do some of the changes. The Bronze Meteors work fine, but the Silver and Gold still don't. I'm honestly unsure what I'm doing wrong.
If you can get back to me as soon as possible, I would greatly appreciate it. Thank you.

https://github.com/MeghanC1470/cart253/blob/master/Exercises/Project3/js/script.js
[https://avatars0.githubusercontent.com/u/54867414?s=400&v=4]<https://github.com/MeghanC1470/cart253/blob/master/Exercises/Project3/js/script.js>
MeghanC1470/cart253<https://github.com/MeghanC1470/cart253/blob/master/Exercises/Project3/js/script.js>
Contribute to MeghanC1470/cart253 development by creating an account on GitHub.
github.com



  *   Meghan Cullen

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
